export const LOCAL_STORAGE_PLATE_SETTINGS = 'LOCAL_STORAGE_PLATE_SETTINGS';
export const LOCAL_STORAGE_THEME = 'LOCAL_STORAGE_THEME';
export const ARRAY_SEPARATOR = '_a_';
export const COMMA_REPLACEMENT = '_c_';
